services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    platform: linux/arm64
    ports:
      - "8000:8000"
    environment:
      - MODEL_PATH=/app/onnx_model_quantized
    networks:
      - mental-health-net
    restart: unless-stopped

networks:
  mental-health-net:
    driver: bridge
