services:
  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MODEL_ID=ekam28/emotion-detector
      - HF_HOME=/app/model_cache
    volumes:
      - model_cache:/app/model_cache
    networks:
      - mental-health-net
    restart: unless-stopped

networks:
  mental-health-net:
    driver: bridge

volumes:
  model_cache:
